language: php

php:
  - 5.4
  - 5.5
  - 5.6
before_script:
  - composer install
script: ./vendor/bin/phpcs --standard=PSR1,PSR2 src/ tests/ bootstrap/ public/ -n && ./vendor/bin/phpunit --coverage-text
